# Generated by Django 4.0.4 on 2022-05-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_myuser_bio_myuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
